In [1]:
%load_ext autoreload
%autoreload 2

This follows the setup of ppd_y1_data.ipynb, but there are some different configurations.  This particular notebook has locations set to the Ohio Supercomputer (and some things like the sys.path.append call below are unnecessary if you are in the `ppd/postprocessing directory`).

In [2]:
import sys
#sys.path.append("/users/PCON0003/cond0080/src/y3-3x2pt-ppd/postprocessing")
import utils_6x2 as util
import utils_ppd as ppd
import utils_ppd_plots as ppd_plots
import utils_ppd_calib as calib
from astropy.io import fits

from tqdm.auto import tqdm, trange

import castor as ca
import pickle

In [3]:
path_ppd = '../'
# path_chain = '../../trimmed_chains/'
path_chain = '../../trimmed_chains_test/'
# path_chain = '/project/projectdirs/des/www/y3_chains/3x2pt/final_paper_chains/'
path_dv = '../../../data/des-y3/'

DATAFILE = '2pt_NG_final_2ptunblind_02_24_21_wnz_covupdate.v2.fits'

fiducial_dv = '2pt_NG_final_2ptunblind_02_24_21_wnz_covupdate.v2.fits'

In [4]:
main_subsets = ['full', '1x2', '2x2', 'xip', 'xim', 'gammat', 'wtheta']

# 3x2 goodness of fit

In [9]:
a = np.loadtxt('../../trimmed_chains/chain_3x2lcdm_0321_boosted.txt')

with open('../../trimmed_chains/chain_3x2lcdm_0321_boosted.txt', 'r') as f:
    header = f.readline()
    
np.savetxt('../../trimmed_chains_test/chain_3x2lcdm_0321_boosted.txt', a[:200000], header=header[2:-1])

In [10]:
with open('../../trimmed_chains_test/chain_3x2lcdm_0321_boosted.txt', 'r') as f:
    print(f.readline())#[1:].split())

# cosmological_parameters--omega_m cosmological_parameters--h0 cosmological_parameters--omega_b cosmological_parameters--n_s cosmological_parameters--a_s cosmological_parameters--omnuh2 shear_calibration_parameters--m1 shear_calibration_parameters--m2 shear_calibration_parameters--m3 shear_calibration_parameters--m4 wl_photoz_errors--bias_1 wl_photoz_errors--bias_2 wl_photoz_errors--bias_3 wl_photoz_errors--bias_4 lens_photoz_errors--bias_1 lens_photoz_errors--bias_2 lens_photoz_errors--bias_3 lens_photoz_errors--bias_4 lens_photoz_errors--bias_5 lens_photoz_errors--width_5 bias_lens--b1 bias_lens--b2 bias_lens--b3 bias_lens--b4 bias_lens--b5 intrinsic_alignment_parameters--a1 intrinsic_alignment_parameters--a2 intrinsic_alignment_parameters--alpha1 intrinsic_alignment_parameters--alpha2 intrinsic_alignment_parameters--bias_ta weight



In [11]:
util.load_cosmosis_chain('../../trimmed_chains_test/chain_3x2lcdm_0321_boosted.txt', verbose=True, read_nsample=False)

Loading chain at
../../trimmed_chains_test/chain_3x2lcdm_0321_boosted.txt
Sampler not found -- non-standard cosmosis output
- using params
['cosmological_parameters--omega_m', 'cosmological_parameters--h0', 'cosmological_parameters--omega_b', 'cosmological_parameters--n_s', 'cosmological_parameters--a_s', 'cosmological_parameters--omnuh2']
- using nsample =  200000


(OrderedDict([('cosmological_parameters--omega_m',
               array([0.3194111 , 0.3168535 , 0.25371432, ..., 0.37049966, 0.35062947,
                      0.35062947])),
              ('cosmological_parameters--h0',
               array([0.66501852, 0.78636815, 0.78168945, ..., 0.56298271, 0.65759626,
                      0.65759626])),
              ('cosmological_parameters--omega_b',
               array([0.06034603, 0.04635131, 0.04334288, ..., 0.03591835, 0.04902424,
                      0.04902424])),
              ('cosmological_parameters--n_s',
               array([0.87789006, 0.99242607, 0.9881779 , ..., 0.98102573, 0.90726056,
                      0.90726056])),
              ('cosmological_parameters--a_s',
               array([1.24664518e-09, 2.03530189e-09, 1.11334044e-09, ...,
                      2.03865530e-09, 1.74281199e-09, 1.74281199e-09])),
              ('cosmological_parameters--omnuh2',
               array([0.00318876, 0.00550417, 0.00495188, ..., 0

In [12]:
RUN_NAME = '3x2lcdm_0321_boosted'
RUN_NAME_PPD = 'fiducial_3x2_goodnessoffit'

res = ppd.load_run(
    path_ppd=path_ppd,
    path_chain=path_chain,
    path_dv=path_dv,
    RUN_NAME=RUN_NAME,
    RUN_NAME_PPD=RUN_NAME_PPD,
    DATAFILE=DATAFILE,
    chunks=200,
    size_chunk=1000,
    data_sets=['xip', 'xim', 'gammat', 'wtheta'],
    load_dvs=False
)


###############################
## Loading chains #############
###############################


Loading list chain at
../fiducial_3x2_goodnessoffit/ppd_chain_3x2lcdm_0321_boosted_fiducial_3x2_goodnessoffit_0.txt
- using params
['cosmological_parameters--omega_m', 'cosmological_parameters--h0', 'cosmological_parameters--omega_b', 'cosmological_parameters--n_s', 'cosmological_parameters--a_s', 'cosmological_parameters--omnuh2', 'cosmological_parameters--w', 'cosmological_parameters--massive_nu', 'cosmological_parameters--massless_nu', 'cosmological_parameters--omega_k', 'cosmological_parameters--tau', 'shear_calibration_parameters--m1', 'shear_calibration_parameters--m2', 'shear_calibration_parameters--m3', 'shear_calibration_parameters--m4', 'wl_photoz_errors--bias_1', 'wl_photoz_errors--bias_2', 'wl_photoz_errors--bias_3', 'wl_photoz_errors--bias_4', 'lens_photoz_errors--bias_1', 'lens_photoz_errors--bias_2', 'lens_photoz_errors--bias_3', 'lens_photoz_errors--bias_4', 'lens_photoz_errors--bias_5', 'lens_photoz_errors--width_1', 'lens_photoz_errors--width_2', 'lens_photoz_errors--

In [ ]:
res_pcal = []

pvals_subsets={k:None for k in['xip','xim', 'gammat','wtheta','1x2','2x2']}

import sys, os

# Disable
def blockPrint():
    sys.stdout = open(os.devnull, 'w')

# Restore
def enablePrint():
    sys.stdout = sys.__stdout__

for _ in trange(10):
    #blockPrint()
    temp = calib.calibrate_pvals(
        path_ppd=path_ppd,
        path_chain=path_chain,
        path_dv=path_dv,
        RUN_NAME=RUN_NAME,
        RUN_NAME_PPD=RUN_NAME_PPD,
        DATAFILE=DATAFILE,
        fiducial_dv=fiducial_dv,
        data_sets_d=['xip','xim', 'gammat','wtheta'],
        data_sets_dprime=['xip','xim', 'gammat','wtheta'],
        N=1000, # 10^4 should give reasonable results, but for memory-sake can try smaller like 100
        title=RUN_NAME_PPD,
            pval_data=res[0]['full'],
        use_pm=True,
#         use_pm=False,
        clip_is=0.1,
        ndraws=1,
        chunks=200,
        size_chunk=1000,
    #     pvals_subsets=res[0],
        #use_logit=(1e-6,1),
        get_zbin_pair_pcal=False,
        pvals_subsets=pvals_subsets,
#         sample_from='fiducial_dv'  # Trying this (different from y1 notebook)
        sample_from='best-fit'  # Trying this (different from y1 notebook)
    )
    res_pcal.append(temp)
    #enablePrint()
    pickle.dump(res_pcal, open('res_pcal_'+RUN_NAME_PPD+'.pickle', 'wb'))
    


###############################
## Loading chains #############
###############################


Loading list chain at
../fiducial_3x2_goodnessoffit/ppd_chain_3x2lcdm_0321_boosted_fiducial_3x2_goodnessoffit_0.txt
- using params
['cosmological_parameters--omega_m', 'cosmological_parameters--h0', 'cosmological_parameters--omega_b', 'cosmological_parameters--n_s', 'cosmological_parameters--a_s', 'cosmological_parameters--omnuh2', 'cosmological_parameters--w', 'cosmological_parameters--massive_nu', 'cosmological_parameters--massless_nu', 'cosmological_parameters--omega_k', 'cosmological_parameters--tau', 'shear_calibration_parameters--m1', 'shear_calibration_parameters--m2', 'shear_calibration_parameters--m3', 'shear_calibration_parameters--m4', 'wl_photoz_errors--bias_1', 'wl_photoz_errors--bias_2', 'wl_photoz_errors--bias_3', 'wl_photoz_errors--bias_4', 'lens_photoz_errors--bias_1', 'lens_photoz_errors--bias_2', 'lens_photoz_errors--bias_3', 'lens_photoz_errors--bias_4', 'lens_photoz_errors--bias_5', 'lens_photoz_errors--width_1', 'lens_photoz_errors--width_2', 'lens_photoz_errors--

Loading realizations from  ../fiducial_3x2_goodnessoffit/ppd_3x2lcdm_0321_boosted_fiducial_3x2_goodnessoffit_0_dprime_theory.npy
 - data vector size = 529
 - number of realizations = 1000
Loading realizations from  ../fiducial_3x2_goodnessoffit/ppd_3x2lcdm_0321_boosted_fiducial_3x2_goodnessoffit_0_dprime_real.npy
 - data vector size = 529
 - number of realizations = 1000
Loading realizations from  ../fiducial_3x2_goodnessoffit/ppd_3x2lcdm_0321_boosted_fiducial_3x2_goodnessoffit_0_d_theory.npy
 - data vector size = 529
 - number of realizations = 1000


###############################
## Sampling data ##############
###############################
Sampling at best-fit with params
cosmological_parameters--omega_m = 0.329
cosmological_parameters--h0 = 0.662
cosmological_parameters--omega_b = 0.0363
cosmological_parameters--n_s = 0.935
cosmological_parameters--a_s = 1.9e-09
cosmological_parameters--omnuh2 = 0.00444
shear_calibration_parameters--m1 = -0.00537
shear_calibration_parameters--m

/global/cfs/cdirs/des/xuod/DES_Y3_3x2/y3-3x2pt/code/ppd/postprocessing/utils_ppd_calib.py:77: NumbaPerformanceWarning: np.dot() is faster on contiguous arrays, called on (array(float64, 2d, A), array(float64, 2d, C))
  return np.dot(A,B)




###############################
## Compute IS weights for d ###
###############################



(200000, 1000)
Neff = 68.2 (median), 16th=29.9, 84th=182.0 (0 were nan's)

###############################
## Computing p-values #########
###############################



1x2
Appending pval for 1x2 0.237653351766374
2x2
Appending pval for 2x2 0.0017173817544873628
gammat
Appending pval for gammat 0.010602210137108202
wtheta
Appending pval for wtheta 0.044395811676178364
xim
Appending pval for xim 0.4086862998541982
xip
Appending pval for xip 0.25343558807428934

###############################
## Calibrated p-values ########
###############################
     - Full         calibrated pval=0.0020 (raw pval=0.0013)
     - 1x2          calibrated pval=0.2180 (raw pval=0.2377)
     - 2x2          calibrated pval=0.0100 (raw pval=0.0017)
     - gammat       calibrated pval=0.0290 (raw pval=0.0106)
     - wtheta       calibrated pval=0.0430 (raw pval=0.0444)
     - xim          calibrated pval=0.4130 (raw pval=0.4087)
     - xip          calibrated pval=0.2200 (raw pval=0.2534)

###############################
## Plotting ###################
###############################

###############################
## Loading chains #############
##################

Loading list chain at
../fiducial_3x2_goodnessoffit/ppd_chain_3x2lcdm_0321_boosted_fiducial_3x2_goodnessoffit_0.txt
- using params
['cosmological_parameters--omega_m', 'cosmological_parameters--h0', 'cosmological_parameters--omega_b', 'cosmological_parameters--n_s', 'cosmological_parameters--a_s', 'cosmological_parameters--omnuh2', 'cosmological_parameters--w', 'cosmological_parameters--massive_nu', 'cosmological_parameters--massless_nu', 'cosmological_parameters--omega_k', 'cosmological_parameters--tau', 'shear_calibration_parameters--m1', 'shear_calibration_parameters--m2', 'shear_calibration_parameters--m3', 'shear_calibration_parameters--m4', 'wl_photoz_errors--bias_1', 'wl_photoz_errors--bias_2', 'wl_photoz_errors--bias_3', 'wl_photoz_errors--bias_4', 'lens_photoz_errors--bias_1', 'lens_photoz_errors--bias_2', 'lens_photoz_errors--bias_3', 'lens_photoz_errors--bias_4', 'lens_photoz_errors--bias_5', 'lens_photoz_errors--width_1', 'lens_photoz_errors--width_2', 'lens_photoz_errors--

Loading realizations from  ../fiducial_3x2_goodnessoffit/ppd_3x2lcdm_0321_boosted_fiducial_3x2_goodnessoffit_0_dprime_theory.npy
 - data vector size = 529
 - number of realizations = 1000
Loading realizations from  ../fiducial_3x2_goodnessoffit/ppd_3x2lcdm_0321_boosted_fiducial_3x2_goodnessoffit_0_dprime_real.npy
 - data vector size = 529
 - number of realizations = 1000
Loading realizations from  ../fiducial_3x2_goodnessoffit/ppd_3x2lcdm_0321_boosted_fiducial_3x2_goodnessoffit_0_d_theory.npy
 - data vector size = 529
 - number of realizations = 1000


###############################
## Sampling data ##############
###############################
Sampling at best-fit with params
cosmological_parameters--omega_m = 0.329
cosmological_parameters--h0 = 0.662
cosmological_parameters--omega_b = 0.0363
cosmological_parameters--n_s = 0.935
cosmological_parameters--a_s = 1.9e-09
cosmological_parameters--omnuh2 = 0.00444
shear_calibration_parameters--m1 = -0.00537
shear_calibration_parameters--m

### With pm

In [ ]:
pvals_rsd = np.concatenate([r[0] for r in res_pcal])

In [ ]:
pvals_rsd.shape

In [ ]:
plt.hist(pvals_rsd, 100);
print(np.sum(pvals_rsd<=0.0013)/10000)

In [ ]:
for key in pvals_subsets.keys():
    _p = np.concatenate([r[1][key] for r in res_pcal])
    print(key, pvals_subsets[key], np.sum(_p<=pvals_subsets[key])/len(_p))
    plt.hist(_p, np.linspace(0,1,100), histtype='step', label=key);
plt.legend()

In [ ]:
pval, dico_indices, ppd_data_obs, ppd_realizations, ppd_theory, weights, ppd_chain, ppd_output_file_basename = res

fig, axes, extra = ppd_plots.ppd_plot_all_obs('xip', 4, 4, '$\\delta \\xi_+(\\theta)$', RUN_NAME+'_'+RUN_NAME_PPD, (2.5, 250.),
         dico_indices,
         all_data=fits.open(os.path.join(path_dv, DATAFILE)),
         all_best_fit=fits.open(os.path.join(path_dv, fiducial_dv)),
         all_realizations=ppd_realizations,
         all_theory=ppd_theory,
         weights=weights, invert_zizj=True, coeff_figsize=0.65, blind_y=True, pcal=pcal, scale_bestfit=True, get_chi2=False)

fig, axes, extra = ppd_plots.ppd_plot_all_obs('xim', 4, 4, '$\\delta \\xi_-(\\theta)$', RUN_NAME+'_'+RUN_NAME_PPD, (2.5, 250.),
         dico_indices,
         all_data=fits.open(os.path.join(path_dv, DATAFILE)),
         all_best_fit=fits.open(os.path.join(path_dv, fiducial_dv)),
         all_realizations=ppd_realizations,
         all_theory=ppd_theory,
         weights=weights, invert_zizj=False, coeff_figsize=0.65, blind_y=True, pcal=pcal, scale_bestfit=True, get_chi2=False)

fig, axes, extra = ppd_plots.ppd_plot_all_obs('gammat', 4, 5, '$\\delta \\gamma_{\\rm t}(\\theta)$', RUN_NAME+'_'+RUN_NAME_PPD, (2.5, 250.),
         dico_indices,
         all_data=fits.open(os.path.join(path_dv, DATAFILE)),
         all_best_fit=fits.open(os.path.join(path_dv, fiducial_dv)),
         all_realizations=ppd_realizations,
         all_theory=ppd_theory,
         weights=weights, invert_zizj=True, coeff_figsize=0.65, blind_y=True, pcal=pcal, scale_bestfit=True, get_chi2=False)

fig, axes, extra = ppd_plots.ppd_plot_all_obs('wtheta', 1, 5, '$\\delta w(\\theta)$', RUN_NAME+'_'+RUN_NAME_PPD, (2.5, 250.),
         dico_indices,
         all_data=fits.open(os.path.join(path_dv, DATAFILE)),
         all_best_fit=fits.open(os.path.join(path_dv, fiducial_dv)),
         all_realizations=ppd_realizations,
         all_theory=ppd_theory,
         weights=weights, invert_zizj=False, coeff_figsize=0.65, blind_y=True, pcal=pcal, scale_bestfit=True, get_chi2=False)

In [ ]:
pval, dico_indices, ppd_data_obs, ppd_realizations, ppd_theory, weights, ppd_chain, ppd_output_file_basename = res

fig, axes, extra = ppd_plots.ppd_plot_all_obs('xip', 4, 4, '$\\delta \\xi_+(\\theta)$', RUN_NAME+'_'+RUN_NAME_PPD, (2.5, 250.),
         dico_indices,
         all_data=fits.open(os.path.join(path_dv, DATAFILE)),
         all_best_fit=fits.open(os.path.join(path_dv, fiducial_dv)),
         all_realizations=ppd_realizations,
         all_theory=ppd_theory,
         weights=weights, invert_zizj=True, coeff_figsize=0.65, blind_y=False, pcal=pcal, scale_bestfit=False, theta_factor=1, get_chi2=False)

fig, axes, extra = ppd_plots.ppd_plot_all_obs('xim', 4, 4, '$\\delta \\xi_-(\\theta)$', RUN_NAME+'_'+RUN_NAME_PPD, (2.5, 250.),
         dico_indices,
         all_data=fits.open(os.path.join(path_dv, DATAFILE)),
         all_best_fit=fits.open(os.path.join(path_dv, fiducial_dv)),
         all_realizations=ppd_realizations,
         all_theory=ppd_theory,
         weights=weights, invert_zizj=False, coeff_figsize=0.65, blind_y=False, pcal=pcal, scale_bestfit=False, theta_factor=1, get_chi2=False)

fig, axes, extra = ppd_plots.ppd_plot_all_obs('gammat', 4, 5, '$\\delta \\gamma_{\\rm t}(\\theta)$', RUN_NAME+'_'+RUN_NAME_PPD, (2.5, 250.),
         dico_indices,
         all_data=fits.open(os.path.join(path_dv, DATAFILE)),
         all_best_fit=fits.open(os.path.join(path_dv, fiducial_dv)),
         all_realizations=ppd_realizations,
         all_theory=ppd_theory,
         weights=weights, invert_zizj=True, coeff_figsize=0.65, blind_y=False, pcal=pcal, scale_bestfit=False, theta_factor=1, get_chi2=False)

fig, axes, extra = ppd_plots.ppd_plot_all_obs('wtheta', 1, 5, '$\\delta w(\\theta)$', RUN_NAME+'_'+RUN_NAME_PPD, (2.5, 250.),
         dico_indices,
         all_data=fits.open(os.path.join(path_dv, DATAFILE)),
         all_best_fit=fits.open(os.path.join(path_dv, fiducial_dv)),
         all_realizations=ppd_realizations,
         all_theory=ppd_theory,
         weights=weights, invert_zizj=False, coeff_figsize=0.65, blind_y=False, pcal=pcal, scale_bestfit=False, theta_factor=1, get_chi2=False)